In [ ]:
#function perform action
#attribute call about function

In [41]:
import numpy as np
array1 = np.array([2, 1, 1, 2])
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array1)
print(array2)
print(array3)
print(array2[1,0])
print(array2)
print(array1[2], array1[3])
print(array1)
print(array3[1,1],array3[2,1])
print(array3)

[2 1 1 2]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
[[1 2 3]
 [4 5 6]]
1 2
[2 1 1 2]
5 8
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array1.size)  #no of elements
print(array2.size)
print(array3.size)
print(array1.shape) #shows no of row and column
print(array2.shape)
print(array3.shape)
print(array1.dtype)
print("Palindrome" if (array1 == array1[::-1]).all() else "Not Palindrome")


1
2
2
4
6
9
(4,)
(2, 3)
(3, 3)
int64
Palindrome


In [39]:
#basic operation arithmentic 
arr=np.array([2,4,6,8],dtype=float)
print(arr)
print(arr+2)
print(arr*2)
print(arr**2)

[2. 4. 6. 8.]
[ 4.  6.  8. 10.]
[ 4.  8. 12. 16.]
[ 4. 16. 36. 64.]


In [52]:
myarr=np.zeros((2,3)) #ypu cancreate by list() or tuple[]
print(myarr)
myarr1=np.ones((2,3))
print(myarr1)
myarr2=np.arange(1,10,2)
print(myarr2)
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [71]:
arr=[2,5,7,8,9]
print(arr)
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[2, 5, 7, 8, 9]
31
9
2
6.2
[2 5 7 8 9]


In [69]:
arr=np.full((2,3),5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [79]:
arr=[2,4,5,6,9]
print(arr)
print(np.sqrt(arr)) #square root
print(np.square(arr)) #square
print(np.abs(arr)) #absolute
print(np.exp(arr)) #exponential
print(np.log(arr)) #log

[2, 4, 5, 6, 9]
[1.41421356 2.         2.23606798 2.44948974 3.        ]
[ 4 16 25 36 81]
[2 4 5 6 9]
[7.38905610e+00 5.45981500e+01 1.48413159e+02 4.03428793e+02
 8.10308393e+03]
[0.69314718 1.38629436 1.60943791 1.79175947 2.19722458]


In [27]:
#production price management system(array)
import numpy as np
arr =np.array([1000, 1200, 1500, 2000, 2300, 2500, 2600, 3000, 500, 190, 300, 310, 750, 800, 950])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

[1000 1200 1500 2000 2300 2500 2600 3000  500  190  300  310  750  800
  950]
19900
1326.6666666666667
3000
190


In [28]:
# Count products
print(np.array(arr))
above1000 = 0
below500 = 0

for price in arr:
    if price > 1000:
        above1000 += 1
    if price < 500:
        below500 += 1

print("Products > 1000:", above1000)
print("Products < 500:", below500)

[1000 1200 1500 2000 2300 2500 2600 3000  500  190  300  310  750  800
  950]
Products > 1000: 7
Products < 500: 3


In [29]:
print(np.array(arr))
search = int(input("Enter price to search: "))

if search in arr:
    print("Price Found")
else:
    print("Price Not Found")

[1000 1200 1500 2000 2300 2500 2600 3000  500  190  300  310  750  800
  950]


Enter price to search:  2000


Price Found


In [30]:
#ascending
print(np.array(arr))
print(np.sort(arr))


[1000 1200 1500 2000 2300 2500 2600 3000  500  190  300  310  750  800
  950]
[ 190  300  310  500  750  800  950 1000 1200 1500 2000 2300 2500 2600
 3000]


In [10]:
#descending
print(np.array(arr))
print(np.sort(arr)[::-1])

[3000 2600 2500 2300 2000 1500 1200 1000  950  800  750  500  310  300
  190]


In [12]:
#20% discount
print(np.array(arr))
discount = arr * 0.8
print(discount)

[ 800.  960. 1200. 1600. 1840. 2000. 2080. 2400.  400.  152.  240.  248.
  600.  640.  760.]


In [26]:
#replace product price new value
print(np.array(arr))
old = int(input("Enter old price: "))
new = int(input("Enter new price: "))

[1800 1200 1500 2000 2300 2500 2600 3000  500  190  300  310  750  800
  950]


Enter old price:  1500
Enter new price:  2890


In [25]:
#final price
print(np.array(arr))
arr[arr == old] = new
print(arr)

[1000 1200 1500 2000 2300 2500 2600 3000  500  190  300  310  750  800
  950]
[1800, 1200, 1500, 2000, 2300, 2500, 2600, 3000, 500, 190, 300, 310, 750, 800, 950]
